server:
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
  paths-to-match:
    - /api/**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
